[project]
name = "sdmx-mcp-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.13.0",
    "sdmx1>=2.22.0",
    "httpx>=0.27.0",
    "certifi>=2024.0.0",
]
